- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: python setup
  include_role:
    name: common
    tasks_from: maven

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd

